const { buildEbayTitle, buildDescription, cleanCategory } = require('./helpers');
function first(...values){return values.find(v=>v!==undefined&&v!==null&&String(v).trim()!=='')||'';}
function joinValue(value){if(Array.isArray(value))return value.filter(Boolean).join(', ');if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>`${k}: ${v}`).join(', ');return String(value||'').trim();}
function addLine(lines,label,value){const text=joinValue(value);if(text)lines.push(`${label}: ${text}`);}
function formatNutrients(n={}){const out=[];for(const [l,v,u] of [['Energie',first(n['energy-kcal_100g'],n['energy-kcal']),'kcal'],['Fett',n.fat_100g,'g'],['davon gesättigte Fettsäuren',n['saturated-fat_100g'],'g'],['Kohlenhydrate',n.carbohydrates_100g,'g'],['davon Zucker',n.sugars_100g,'g'],['Eiweiß',n.proteins_100g,'g'],['Salz',n.salt_100g,'g']])if(v!==undefined&&v!==null&&v!=='')out.push(`${l}: ${v} ${u}/100 g`);return out.join('\n');}
function mapOpenFoodFacts(raw,ean){if(raw.status===0||!raw.product)return null;const i=raw.product,name=first(i.product_name_de,i.product_name,i.generic_name_de,i.generic_name),brand=first(i.brands,i.brand_owner),manufacturer=first(i.brand_owner,i.manufacturer,i.manufacturing_places),size=first(i.quantity,i.product_quantity?`${i.product_quantity}${i.product_quantity_unit||''}`:'');const tech=[];addLine(tech,'Allgemeine Bezeichnung',first(i.generic_name_de,i.generic_name));addLine(tech,'Füllmenge / Menge',size);addLine(tech,'Verpackung',first(i.packaging_text_de,i.packaging_text,i.packaging));addLine(tech,'Zutaten',first(i.ingredients_text_de,i.ingredients_text));addLine(tech,'Allergene',first(i.allergens_from_ingredients,i.allergens));addLine(tech,'Herkunft',first(i.origins_de,i.origins));addLine(tech,'Herstellungsorte',i.manufacturing_places);addLine(tech,'Labels / Zertifizierungen',first(i.labels_de,i.labels));addLine(tech,'Nutri-Score',i.nutriscore_grade?String(i.nutriscore_grade).toUpperCase():'');addLine(tech,'Nährwerte',formatNutrients(i.nutriments));const p={ean,name,brand,manufacturer,category:cleanCategory(first(i.categories_de,i.categories,i.pnns_groups_2,i.pnns_groups_1)),color:first(i.color,i.colors),size,material:first(i.packaging_materials,i.packaging_text_de,i.packaging_text,i.packaging),product_number:first(i.mpn,i.model,i.product_number),technical_data:tech.join('\n'),compatibility:'',oem_numbers:'',condition:'Neu',condition_description:'Neuware. Verpackungszustand und Mindesthaltbarkeitsdatum bitte vor Veröffentlichung prüfen.',source:'Open Food Facts',image_url:first(i.image_front_url,i.image_url,i.image_front_small_url)};p.ebay_title=buildEbayTitle(p);p.description=buildDescription(p);return p;}
function mapGeneric(raw,ean){const i=raw.product||raw.items?.[0]||raw.products?.[0]||raw;if(!i||typeof i!=='object')return null;const specs=i.specifications&&typeof i.specifications==='object'?Object.entries(i.specifications).map(([k,v])=>`${k}: ${joinValue(v)}`).join('\n'):joinValue(i.specifications);const p={ean,name:first(i.title,i.name,i.product_name),brand:first(i.brand,i.brands),manufacturer:first(i.manufacturer,i.company,i.brand_owner),category:cleanCategory(first(i.category,i.category_name,i.categories)),color:first(i.color,i.colour),size:first(i.size,i.quantity,i.dimensions),material:first(i.material,i.materials),product_number:first(i.mpn,i.model,i.part_number,i.product_number),technical_data:[joinValue(i.description),specs].filter(Boolean).join('\n'),compatibility:joinValue(first(i.compatibility,i.fitment)),oem_numbers:joinValue(first(i.oem_numbers,i.oe_numbers)),condition:'Neu',condition_description:'',source:'externe Produkt-API',image_url:first(i.image_url,i.image,i.images?.[0]?.url,i.images?.[0])};p.ebay_title=buildEbayTitle(p);p.description=buildDescription(p);return p;}
function parseUrls(configured=''){return String(configured||process.env.PRODUCT_API_URLS||process.env.PRODUCT_API_URL||'https://world.openfoodfacts.org/api/v2/product/{ean}.json').split(/[\r\n;]+/).map(v=>v.trim()).filter(Boolean);}
async function lookupExternalProduct(ean,configured){const urls=parseUrls(configured);const errors=[];for(const template of urls){try{const url=template.replaceAll('{ean}',encodeURIComponent(ean));const headers={Accept:'application/json','User-Agent':'AMA-Produktmanager/4.0'};const key=process.env.PRODUCT_API_KEY;if(key)headers[process.env.PRODUCT_API_KEY_HEADER||'Authorization']=`${process.env.PRODUCT_API_KEY_PREFIX||''}${key}`;const response=await fetch(url,{headers,signal:AbortSignal.timeout(15000)});if(response.status===404)continue;if(!response.ok)throw new Error(`HTTP ${response.status}`);const raw=await response.json();const product=(url.includes('openfoodfacts.org')||Object.hasOwn(raw,'status_verbose'))?mapOpenFoodFacts(raw,ean):mapGeneric(raw,ean);if(product&&product.name)return product;}catch(e){errors.push(`${template}: ${e.message}`);}}if(errors.length===urls.length&&urls.length)throw new Error('Keine Produktquelle erreichbar: '+errors.join(' | '));return null;}
module.exports={lookupExternalProduct};
